### ISSUE TITLE
hint for if blue tile doesn't let you spill soup on the painting

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#117]

**Comment by CONKINGTON** [comment]
p: Come on this has so much blue I'm feeling seasick.
t: Ahoy me matey! Welcome to the treacherous waters of the Blue Exhibit, or are you a mere landlubber laid out to dry?
p: Why are pretending to be a pirate: this is various shades of blue.
t: Just wanted to polish up my Blackbeard impression, didn't know you were easily frustrated.
p: Well, I didn't know either until you were cracking quips every time I pause.
t: Just wanting to make sure you stay fit for whatever may come your way!
t: No fun having an unprepared rival-
p: Hey cool it with the remarks!
t: so I may give words of encouragement.
p: God I wish Lapis Lalooney can take a break long enough for me to stain this painting, he goes on and on about how he doesn't like the paintings because they are blue and instead because of their Jenny Sequoia-
t: I think you meant je ne sais quoi.
p: whatever, he is in such denial.
t: That is the tragedy of passions: they can take over you if you ain't careful.
t: Who knows, maybe he would, say, get easily offended if his precious blues got slandered.

**Comment by pixequil** [comment]
Toasty is not inside the blue exhibit

**Comment by funnyboy044** [comment]
I like the pirate angle if we want to do something with that

**Comment by CONKINGTON** [comment]
> Toasty is not inside the blue exhibit

She is Posty's mindddd

**Comment by CONKINGTON** [comment]
p concerned "Come on this has so much blue I'm feeling seasick."
t enthused "Ahoy me matey! Welcome to the treacherous waters of the Blue Exhibit: can you thrive amidst the high ocean or will you be a mere landlubber treading water?"
p annoyed "Why are pretending to be a pirate: this is various shades of blue."
t smug "Who sayeth aye was pretending? I didn't know ye were of short temper."
p "Well, I didn't know either until you were cracking quips every time I pause."
t smug2 "It's no fun having to fight a weakling who doesn't know the scent of danger from booty!"
t "No fun having an unprepared rival-"
p angry "Hey cool it with the remarks!"
t crossedarms "so I may champion you with fighting words."
p "God I wish Lapis Lalooney can take a break long enough for me to stain this painting, he goes on and on about how he doesn't like the paintings because they are blue and instead because of their Jenny Sequoia-"
t smug2 "I think ye meant je ne sais quoi."
p annoyed "whatever, he is in such denial."
t "That is the tragedy of passions: they can taketh over you if ye ain't careful."
t "Who knoweth, maybe he would, say, become easily offended if his precious blues hath been slandered..."
t "A dead man tells no tales..."
p suspicious "Note to self: never talk about being seasick in the Blue Exhibit."
p "Toasty will bust out her terrible pirate accent."

**Comment by pixequil** [comment]
assigned to AnArtichoke

**Comment by pixequil** [comment]
https://docs.google.com/document/d/1WhRUQwlUWJ4uZUPKA1kMKDqoVJVSBf-UWJIuxX7-DIQ/edit
