### ISSUE TITLE
conversation where yd implies they want to get into advertising

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#15]
https://github.com/pixequil/oso-game-1/blob/bda13de7f02e91e6fd348a40107169783d0e5c67/game/room001-mainstreet.rpy#L113

**Comment by CONKINGTON** [comment]
yd: "Ah Posty, nice to meet you ag-"
yd: "..."
yd: "Who is following you?"
p: "Well, this is Brand Soda-"
bs: "Hello"
p:" They started following me around after I listened to their story."
bs: "I have been tragically shut out of stardom because I was too forward thinking for the citizens of this town."
yd: "Oh dear, how tragic."
bs: "Now I am stuck in this place without a single penny or crumb in my name."
yd: "What do you do for a living?"
bs: "Well when I am not busy being stuck in the middle of a town, I often serve as a spokesperson for various brands."
yd: "Oh that is an interesting career choice: going around with a bit of flash and pizzazz."
bs: "Yep, it can reach those highs very well, although it requires a lot of work."
yd: "Wellllll, I do have a business venture that I recently started."
bs:"Oh very entrepreneurial of you, how is that going?"
yd: "Well it is chugging along: I have already got a few paying customers I knew from back in pilot school."
yd: "Already getting a steady flow of business. In fact, I am very confident it could go national!"
yd: "It just needs a bit of a push to really take off."
p: "Hehehe plane pun."
yd: "However, I need to rethink the PR stuff: go beyond the circle of friends."
bs: "What is wrong with the PR stuff?"
yd: "How can I say this? It is a bit too techinical for the average joe schmo."
yd: "Lacks that flair that a charismatic spokesperson brings..."
bs: "Well sorry for being a bit brazen, but are you looking for a spokesperson at the moment?"
bs: "Perhaps someone with experience?"
yd: "Well we went through a dozen of candidates so far, but none of them felt like you can share a bowl of nachos with:"
yd: "Either they were rather dry or trying too hard to seem cool. Hadn't found it yet."


-credit as XKZ

**Comment by funnyboy044** [comment]
yd "HIIIIIIIIIII!"
        p suspicious "Uhh...hi."
        yd "Can we be best friends?"
        p neutral "I don't know, kid. I'm too busy."
        yd "That's OK!"
        p "Where are your parents?"
        yd "Is that a type of vegetable?"
        p "Never mind."
        p "What are you doing out by yourself?"
        yd "I'm an entrée-prenur!"
        p suspicious "For what?"
        yd "Flying lessons for people who don't know how to fly! It'll be the best thing yet!"
        yd "But I need a best fwiend to help me out with the buies-ness and give advice!"
        p "You mean business?"
        yd "Buies-ness is French!"
        yd "But I won't just take anybody to be my best friend! I have very special spec-sip-uh-kay-shuns!"
        yd "Number 1: They should have a lot of charisma."
        yd "Not too dry or trying too hard to be cool. Just enough to make me laugh!"
        yd "Number B: They should have a lot of bouis-ness experience. Flying can be pretty technical for people to understand!"
        yd "And Number C..."
        yd "They should feel like you wanna share nachos with them."
        yd "I really like nachos."
        yd "But I haven't found anyone yet!"
        p neutral "Well if I find anyone to help your business take off, I'll let you know."
        yd "Hehehe flying pun! Thanks mail gal!"
