### ISSUE TITLE
posty talks to buff and removes hamburger fire

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#160]
Posty talks to Buff. 

Buff Loves history. Tells you all about history and the paintings and people in the room. Doesn't actually know anythving about history but Posty doesn't either so it's hard to call them out on it.

buff makes up some kind of fact about the painting.

posty thinks to use the heavier on the painting, removing the fire.

posty prods buff for another fact about the painting, that is now changed.

buff makes up a new fact that contradicts the previous fact.

posty calls them out on the contradiction, causing them to give posty an imaginary lighter.

posty is confused.

buff explains that imaginary things are a contradictory science, so they gave Posty a con-science lighter to make their conscience lighter after saying a contradiction outing themself as a liar. this all sounds very made-up, but, that's the nature of imaginary things.

**Comment by CONKINGTON** [comment]
p happy "Ooh you seem to know a lot about art!"
buff "Why thank you! I am a fanatic when it comes to these things!"
buff "The food exhibit in particular is one of the oldest collection of pre OSO artwork in the world, some of them dating back thousands of years!"
p astonished "Thousands of years?!"
buff "Indeed. Take this firey masterpiece here!"
"Abandoned In The Grill: the fire really wants to escape the canvas!"
buff "This painting shows the very last moments of the artist who had painted it."
buff "If you listen closely, you can hear faint crackling and screams..."
p concerned "..."
buff "As though he is still burning alive in that August evening..."
p suspicious "(I may not know what watercolor is, but they are bluffing!)"
p "(Maybe I should try out this heavier thing, just in case...)"
    show burger out
    $ item.heavier = False
    $ burger_extinguish = True
p happy "Wow you have a lot of knowledge about this exhibit!"
p "Tell me more about this Abandoned in the Grill piece."
buff "Why.. er certainly"
buff "It is a misconception that this particular piece is called Abandoned in the Grill because the artist died in a fire..."
p suspicious "Oh?"
buff "Yeah yeah err it was because..."
p "Yes?"
buff "The artist was being torn from limb to limb by a... burger that became alive!"
buff "Yeahh yeah yea..."
p "But I just remember you telling me with absolute certainty you can hear faint crackling if you listen closely enough!"
buff "Ahhhuhuhuh... it was thematic!"
p angry "You are pulling my flap."
buff "You finally caught me..."
    $ item.imaginary_lighter = True
    "You got the {b}imaginary lighter{/b}!
p confused "Huh?"
buff "The imaginary and illusory don't follow our rules as much as they evade them."
buff "To make a lie requires the liar to know what looks true."
buff "You have caught me in a contradiction of my own making, you know this contradictory science like the back of your hand!"
buff "Making your conscience lighter in the end of it..."
buff "Con-science lighter, contradictory science lighter..."
p angry "I see"
