### ISSUE TITLE
first Red Tile conversation.

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#40]
```
    p "_" # TODO: first Red Tile conversation.
```

https://github.com/pixequil/oso-game-1/blob/4a7f7a45ae16f5ff6c209df539b1f7a2bfad9690/game/room004-museum_blue.rpy#L42

**Comment by pixequil** [comment]
https://github.com/pixequil/oso-game-1/blob/c9953ec3e6480bd1dfa989c34c13f39644383997/game/room004-museum_blue.rpy#L42-L50

**Comment by CONKINGTON** [comment]
rt: "What do you want from me: I was just about to make a remark about the incessant use of blue in this exhibit."
p: "Well-
rt: "Let me guess: you are confused about my very presence in this area."
p: "Yeah, but-"
rt: "Well I have a long and complex history with this exhibit and the curators who ruined it."
rt: "Long before its desecration by Big Blue, this gallery was once known for its wide array of red and vermillion."
rt: "For miles and miles, you can see the culmination of hours poured into the worship of the most delectable primary."
rt: "For instance, there was a nice piece which depicted a glorious autumn scene in dabs of scarlet and crimson dancing among the cerise earth."
rt: "Another piece was a striking self portait which was heightened by the calculated use of fire engine alongside carmine, creating a beaut of an abstraction."
rt: "It was the height of art!"
p: "Yeah, I better get goi-"
rt: "You want to know what happened to such a veritable storage of culture? 
rt: "It was dumped into some dusty archive for some crackpotted idea for a "blue period".
rt: "Countless examplars of colour use, condemned to permanent darkness because uncultured swinish rubes who couldn't tell the difference between garnet and salmon pink ate up this garish mess."
rt: "I mean, it absolutely claws at my cultural soul to watch that fucking Blue Tile jump up and down every single day."
rt: "You know how much my life seeps away every time I hear that twat acting like these paintings have the slightest etch of artistic integrity in them? It burns!"
rt: "So I began scheming a way to bring back the red gallery: what if the exhibit were to stop because of an... accident?"
rt: "Lets say, one of the vistors has _accidentally_ spilled something over the pieces. That would be a tragic thing to happen..."
p: "You attempted to spill something, didn't you?"
rt: "Wha- uh no."
p: "..."
rt: "Well, I maybe had a little accident."
rt: "A tiny scoop of miso soup for the starving art... pieces."
p: "Yeaaaah, suuuure."
rt: "Besides, it wasn't like I was defacing them..."
rt: "You could think of it as an improvement, like those art restorers who put pieces back to new."
rt: "Anyway, all the soup did was rust the gates, which was the only redeeming quality this exibhit has, and I think the security guard has it out for me so I would extremely appreciate it if you can accept this gift from me as a token of red appreciation and blue disdan."

**Comment by f4nimator** [comment]
tweaked it a bit so it would work in the code, add emotions and remove the swear words
```
        redtile "What do you want from me? I was just about to make a remark about the incessant use of blue in this exhibit."
        p "Well-"
        redtile "Let me guess: you are confused about my very presence in this area."
        p concerned "Yeah, but-"
        redtile "Well I have a long and complex history with this exhibit and the curators who ruined it."
        redtile "Long before its desecration by Big Blue, this gallery was once known for its wide array of red and vermillion."
        redtile "For miles and miles, you can see the culmination of hours poured into the worship of the most delectable primary."
        redtile "For instance, there was a nice piece which depicted a glorious autumn scene in dabs of scarlet and crimson dancing among the cerise earth."
        show posty confused
        redtile "Another piece was a striking self portait which was heightened by the calculated use of fire engine alongside carmine, creating a beaut of an abstraction."
        redtile "It was the height of art!"
        p confused "Yeah, I better get goi-"
        redtile "You want to know what happened to such a veritable storage of culture?"
        redtile "It was dumped into some dusty archive for some crackpotted idea for a 'blue period'."
        redtile "Countless examplars of colour use, condemned to permanent darkness because uncultured swinish rubes who couldn't tell the difference between garnet and salmon pink ate up this garish mess."
        redtile "I mean, it absolutely claws at my cultural soul to watch that damn Blue Tile jump up and down every single day."
        redtile "You know how much my life seeps away every time I hear that idiot acting like these paintings have the slightest etch of artistic integrity in them? It burns!"
        redtile "So I began scheming a way to bring back the red gallery: what if the exhibit were to stop because of an... accident?"
        redtile "Lets say, one of the vistors has {i}accidentally{/i} spilled something over the pieces. That would be a tragic thing to happen..."
        p suspicious "..So you attempted to spill something?"
        redtile "Wha- uh no."
        p neutral quiet "..."
        redtile "Welll.. I maybe had a little accident."
        redtile "A tiny scoop of miso soup for the starving art... pieces."
        p suspicious "Yeaaaah, suuuure."
        redtile "Besides, it wasn't like I was defacing them!"
        redtile "You could think of it as an improvement, like those art restorers who put pieces back to new.."
        redtile "Anyway, all the soup did was rust the gates, which was the only redeeming quality this exhibit has."
        # TODO: #40 first Red Tile conversation. Red Tile is A grumpy character that absolutely hates this exhibit, and is mostly here out of spite. They have previously thrown some Miso Soup at one of the paintings, leaving its gate rusted, but managed to avoid the blame for it. Regardless, they’re not trying to draw too much attention to themselves. They also have some choice words about Blue Tile.
        redtile "I'm sure the security guard has it out for me though, so I would extremely appreciate it if you can accept this gift from me. A token of red appreciation and blue disdan if you will."
        # Red Tile gives you the soup ladle, They’re very interested in getting rid of the incriminating evidence.
        $ item.ladle_empty = True
        show ladle_empty # TODO: #41 ladle, empty and filled with soup versions
        show posty concerned
        "You got the {b}ladle{/b}!{p}You feel guilty just carrying it..."
        jump museum_blue
```

**Comment by funnyboy044** [comment]
Tried my hand at rewriting this to fit in a little better with the story while sticking to what @f4nimator wrote
        redtile "What do you want from me? I was just about to make a remark about the incessant use of blue in this exhibit."
        p "Well-"
        redtile "Let me guess. You are confused about my very presence in this area."
        p concerned "Yeah, but I assumed you were friends with Blue Tile and you went to check out the exhibit together."
        redtile "Uggh, not even close. Blue dragged me out here so he couldn't ramble on about this dumb, irritating, meaningless color to himself.
        redtile "As for the exhibit, if you knew anything about its long and complex history, you would know it represents the death of free artistic expression and pandering to the masses."
        p confused "What?"
        redtile "Let me tell you a story."
        redtile "Long before its desecration, this gallery was once known for its wide array of red and vermillion."
        redtile "For miles and miles, you could see the culmination of hours poured into the worship of the most delectable primary."
        redtile "For instance, there was a nice piece which depicted a glorious autumn scene in dabs of scarlet and crimson dancing among the cerise earth."
        redtile "Another piece was a striking self portait, heightened by the calculated use of fire engine red alongside carmine, creating a beautiful abstraction."
        redtile "It was the height of art!"
        redtile "You want to know what happened to such a veritable storage of culture?"
        redtile "It was dumped into some dusty archive for some crackpot idea for a \"blue period\"."
        redtile "Countless examplars of colour use, condemned to permanent darkness because uncultured swinish rubes who couldn't tell the difference between garnet and salmon pink ate up this garish mess."
        redtile "I mean, it absolutely claws at my cultural soul to watch Blue Tile rave up and down about this every single day.
        redtile "Do you know how much of my life seeps away every time I hear that idiot acting like these paintings have the slightest etch of artistic integrity in them? It hurts!"
        redtile "So, I began scheming a way to get back at the blue gallery: what if the exhibit were to have an...accident?"
        redtile "Such as lets say, one of the vistors {i}accidentally{/i} spilled something over the art pieces? That would be a tragic thing to happen..."
        p suspicious "So you attempted to spill something on the art?"
        redtile "Wha- uh, no."
        p "Yeaaaah, suuuure."
        redtile "Well...there was maybe a little accident."
        redtile "A tiny scoop of miso soup for the starving art...pieces."
        redtile quiet "..."
        redtile "Promise you'll keep this next part a secret?"
        p suspicious "OK..."
        redtile "Yes, it was me. I brought some miso soup from home and tried to throw it on the art when Bluey wasn't looking."
        redtile "Besides, it wasn't like I was defacing them!"
        redtile "You could think of it as an improvement, like those art restorers who put pieces back to new."
        redtile "Anyway, all the soup did was rust the gates, which was really the only redeeming quality about this exhibit."
        redtile "I'm sure the security guard has it out for me though. Someone else took the blame, but I still have the evidence on me."
        redtile "I need to get rid of it before he sees it, but I can't risk drawing attention to myself."
        redtile "Actually, here! You take it!"
        # Red Tile gives you the soup ladle, They’re very interested in getting rid of the incriminating evidence.
        $ item.ladle_empty = True
        show ladle_empty # TODO: #41 ladle, empty and filled with soup versions
        show posty concerned
        "You got the {b}ladle{/b}!{p}You feel guilty just carrying it..."
        p "What do I do with it?"
        redtile "I would extremely appreciate it if you get that ladle as far away from here as you can."
        redtile "Think of it as a token of red appreciation and blue disdain, if you will."
        p "OK, well, talk to you later."
