### ISSUE TITLE
game start hint

### ISSUE THREAD

**Issue by pixequil** [pixequil/oso-game-1#6]
https://github.com/pixequil/oso-game-1/blob/7ed8e604918bf90643c4692a0f084f953b988177/game/yd_hints.rpy#L18

**Comment by pixequil** [comment]
accidentally closed this instead of #8

**Comment by CONKINGTON** [comment]
**Game Start Hints**
yd: "Cash is king here: collect bundles to progress!"
yd: "In the event of an emergency landing, pray as loud as you can to ensure salvation for your fellow passengers."
yd: "If you are stuck, you can get Toasty to help you unintentionally!"
yd: "Some may require a bit of convincing for their assistance, so be prepared to go on a quest for them."
yd: "Never use a fork in a toaster: worst mistake I ever made."
yd: "There used to be three Tiles in the city: Red, Blue and Green."
yd: "Always eat before you go to the Food Exhibit: it is unbearable on an empty stomach."

-credit as XKZ

**Comment by CONKINGTON** [comment]
Here are some more:
yd: "When in doubt, click about!"
yd: "This game wouldn't be possible without the volunteers at OSO! Join them at https://discord.gg/h4NvE5pdDJ for more!"
yd: "Collect records to hear soundtracks at the Music Store: they are lying all over the city. Some consider them a tripping hazard."
yd: "Never ask Ahiss what happened to their kingdom: it is a sore point."
yd: "If you ever feel the urge to be a bird, you may be a yellow cat."
yd: "If you squint hard enough, you can see secret messages everywhere in this game. Pretty cool huh?"
yd: "As the official spokesperson of OSO: The Game, the next DLC will include multiplayer and the chance to meet Crayon Box in battle. Well, I was kidding about being the spokesperson of OSO: I am just an intern, but you believed me for a second"
yd: "Watashi wa Yellow Diamond desu, anata mo Yellow Diamond dewa arimasen."
yd: "If you look at me long enough, I'll look back."
yd: "Nothing bad ever happens to the Diamonds!"
yd: "LALALALALALALA I CAN'T HEAR YOU!!!"
yd: "This game hint is sponsored by Brand Soda's Marketing Course: bring charisma and charm into your daily life with Brand Soda's patented B.E.G technique! For only $19, you too can sell dreams to a sleeper and the time to a clock with the discount code YELLOWDIAMOND19."
yd: "Sometimes I may speak a bit obliquely at the start up screen. It gets boring waiting around for someone to open up the game so I write a couple of unique lines to spice things up."
yd: "Whatever you do, never trust kind strangers who promise you immortality and riches: dear friend of mine did that once, ended up in some cybernetic hellscape because he didn't read the fine print!"
yd: "When you feel like everything is about to fall, repeat this in your head: you will be fine."
yd: "[This game hint has been seized by the OSO Municipal Council for public safety violations]

**Comment by pixequil** [comment]
sorry, this is my bad; i left this one without instructions. this is the hint that toasty gives if you talk to her immediately after starting the game, before taking any other action. it should encourage the player to explore and interact with anything and everything they see

**Comment by CONKINGTON** [comment]
Oh ok

t: Oh hey, what'cha need?
p: I am not very sure about this parcel delivery business sometimes, keep getting lost and all that-
t: uh huh.
p: how can I do this? 
t: Glad you asked! Here at OSO we have a mantra: "When in doubt, click about!".
p: When in doubt, what about?
t: It is an anachronism, don't mind it.
t: Basically press on every button, twist every knob and mess around with all the options you know! Just try everything and see if it works!
p: Oh, I guess that is worth a shot...
t: Attaboy! You are going to shape up as a potent rival in no time!
